import jsPDF from 'jspdf';

/**
 * Clean, executive-styled PDF report generator for the AI Research Funding & Innovation Platform.
 */

const addHeader = (doc, title, subtitle) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header Banner background
  doc.setFillColor(15, 23, 42); // #0f172a Deep Slate
  doc.rect(0, 0, pageWidth, 28, 'F');
  
  // Brand title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('AI RESEARCH & INNOVATION PLATFORM', 14, 14);
  
  // Document title right aligned
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(title.toUpperCase(), pageWidth - 14, 14, { align: 'right' });
  doc.text(subtitle || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }), pageWidth - 14, 21, { align: 'right' });
  
  // Accent line
  doc.setDrawColor(99, 102, 241); // Indigo #6366f1
  doc.setLineWidth(1.5);
  doc.line(0, 28, pageWidth, 28);
};

const addFooter = (doc, pageNum, totalPages) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 12, pageWidth - 14, pageHeight - 12);
  
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Confidential - Generated by AI Research Funding & Innovation Platform', 14, pageHeight - 6);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 14, pageHeight - 6, { align: 'right' });
};

/**
 * 1. Export Executive Dashboard Summary PDF
 */
export const exportDashboardPDF = (stats, patentStats) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  addHeader(doc, 'Executive Dashboard Summary', 'Analytics & KPI Report');
  
  let y = 38;
  
  // Section Title
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Platform Metrics Overview', 14, y);
  y += 8;
  
  // KPI Summary Cards Box
  const summaryCards = [
    { label: 'Total Researchers', val: stats?.summary?.totalResearchers || 0 },
    { label: 'Funding Opportunities', val: stats?.summary?.fundingOpportunities || 0 },
    { label: 'Total Publications', val: stats?.summary?.totalPublications || 0 },
    { label: 'Patent Documents', val: patentStats?.totalPatents || 0 },
  ];
  
  const cardWidth = (pageWidth - 28 - 9) / 4;
  summaryCards.forEach((c, idx) => {
    const x = 14 + idx * (cardWidth + 3);
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, y, cardWidth, 22, 2, 2, 'FD');
    
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text(c.label.toUpperCase(), x + 4, y + 7);
    
    doc.setFontSize(14);
    doc.setTextColor(99, 102, 241);
    doc.setFont('helvetica', 'bold');
    doc.text(String(c.val), x + 4, y + 17);
  });
  
  y += 30;
  
  // Section: Funding Distribution by Domain
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Funding Allocation by Domain', 14, y);
  y += 6;
  
  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 8, 'F');
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.setFont('helvetica', 'bold');
  doc.text('Research Domain', 18, y + 5.5);
  doc.text('Opportunities', 110, y + 5.5, { align: 'right' });
  doc.text('Total Funding ($)', pageWidth - 18, y + 5.5, { align: 'right' });
  y += 8;
  
  doc.setFont('helvetica', 'normal');
  (stats?.fundingDistribution || []).forEach((row, i) => {
    if (i % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(14, y, pageWidth - 28, 7, 'F');
    }
    doc.setTextColor(15, 23, 42);
    doc.text(row.domain || 'N/A', 18, y + 5);
    doc.text(String(row.opportunityCount), 110, y + 5, { align: 'right' });
    doc.text(`$${Number(row.totalFunding).toLocaleString()}`, pageWidth - 18, y + 5, { align: 'right' });
    y += 7;
  });
  
  y += 10;
  
  // Section: Patent Landscape Overview
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Patent Intelligence Overview', 14, y);
  y += 6;
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text(`• Active Granted Patents: ${patentStats?.activePatents || 0}`, 18, y);
  doc.text(`• Pending Applications: ${patentStats?.pendingPatents || 0}`, 18, y + 5);
  doc.text(`• Top Patent Holders: ${(patentStats?.topAssignees || []).map(a => a.assignee).join(', ') || 'N/A'}`, 18, y + 10);
  
  y += 20;
  
  addFooter(doc, 1, 1);
  doc.save(`Executive_Dashboard_Summary_${new Date().toISOString().slice(0, 10)}.pdf`);
};

/**
 * 2. Export Funding Opportunities Report PDF
 */
export const exportFundingPDF = (opportunities, filters = {}) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  addHeader(doc, 'Funding Opportunities', 'Discovery & Eligibility Match');
  
  let y = 38;
  
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Funding Grants & Opportunities Report', 14, y);
  y += 6;
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Search Criteria: ${filters.search || 'All'} | Domain: ${filters.domain || 'All Domains'} | Total Results: ${opportunities.length}`, 14, y);
  y += 10;
  
  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 8, 'F');
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.setFont('helvetica', 'bold');
  doc.text('Title & Organization', 18, y + 5.5);
  doc.text('Domain', 115, y + 5.5);
  doc.text('Amount ($)', 160, y + 5.5, { align: 'right' });
  doc.text('Deadline', pageWidth - 18, y + 5.5, { align: 'right' });
  y += 9;
  
  doc.setFont('helvetica', 'normal');
  opportunities.forEach((opp, i) => {
    if (y > 260) {
      addFooter(doc, doc.internal.getNumberOfPages(), doc.internal.getNumberOfPages());
      doc.addPage();
      addHeader(doc, 'Funding Opportunities', 'Discovery & Eligibility Match');
      y = 38;
    }
    
    if (i % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(14, y - 1, pageWidth - 28, 12, 'F');
    }
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    const truncatedTitle = opp.title.length > 50 ? opp.title.substring(0, 48) + '...' : opp.title;
    doc.text(truncatedTitle, 18, y + 4);
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(opp.organization || 'N/A', 18, y + 8.5);
    
    doc.setTextColor(51, 65, 85);
    doc.text(opp.research_domain || 'General', 115, y + 5);
    
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129); // Emerald
    doc.text(`$${Number(opp.funding_amount).toLocaleString()}`, 160, y + 5, { align: 'right' });
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(opp.deadline ? new Date(opp.deadline).toLocaleDateString() : 'Rolling', pageWidth - 18, y + 5, { align: 'right' });
    
    y += 13;
  });
  
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addFooter(doc, p, totalPages);
  }
  
  doc.save(`Funding_Opportunities_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};

/**
 * 3. Export Patent Results Report PDF
 */
export const exportPatentsPDF = (patents, stats) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  addHeader(doc, 'Patent Intelligence', 'Intellectual Property Landscape');
  
  let y = 38;
  
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Patent Intelligence & IP Portfolio Report', 14, y);
  y += 6;
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Total Patents Analyzed: ${patents.length} | Granted: ${stats?.activePatents || 0} | Pending: ${stats?.pendingPatents || 0}`, 14, y);
  y += 10;
  
  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 8, 'F');
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.setFont('helvetica', 'bold');
  doc.text('Patent ID / Title', 18, y + 5.5);
  doc.text('Assignee & Inventor', 110, y + 5.5);
  doc.text('Domain', 160, y + 5.5);
  doc.text('Status', pageWidth - 18, y + 5.5, { align: 'right' });
  y += 9;
  
  patents.forEach((pat, i) => {
    if (y > 260) {
      addFooter(doc, doc.internal.getNumberOfPages(), doc.internal.getNumberOfPages());
      doc.addPage();
      addHeader(doc, 'Patent Intelligence', 'Intellectual Property Landscape');
      y = 38;
    }
    
    if (i % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(14, y - 1, pageWidth - 28, 12, 'F');
    }
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    const patentIdStr = pat.patent_number ? `[${pat.patent_number}] ` : '';
    const titleStr = patentIdStr + pat.title;
    const truncatedTitle = titleStr.length > 45 ? titleStr.substring(0, 43) + '...' : titleStr;
    doc.text(truncatedTitle, 18, y + 4);
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Filing Year: ${pat.filing_year || 'N/A'}`, 18, y + 8.5);
    
    doc.setTextColor(51, 65, 85);
    const assigneeStr = pat.assignee || pat.inventors || 'N/A';
    doc.text(assigneeStr.length > 25 ? assigneeStr.substring(0, 23) + '...' : assigneeStr, 110, y + 5);
    
    doc.text(pat.technology_domain || 'General Tech', 160, y + 5);
    
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(pat.status === 'Active' ? 16 : 245, pat.status === 'Active' ? 185 : 158, pat.status === 'Active' ? 129 : 11);
    doc.text(pat.status || 'Active', pageWidth - 18, y + 5, { align: 'right' });
    
    y += 13;
  });
  
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addFooter(doc, p, totalPages);
  }
  
  doc.save(`Patent_Landscape_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};

/**
 * 4. Export Research Insights & Trends PDF
 */
export const exportResearchTrendsPDF = (trendsData) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  addHeader(doc, 'Research Intelligence', 'Publications & Domain Velocity');
  
  let y = 38;
  
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Research Trends & Domain Analytics Report', 14, y);
  y += 6;
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Tracked Research Domains: ${trendsData?.domains?.length || 0} | Date Generated: ${new Date().toLocaleDateString()}`, 14, y);
  y += 10;
  
  // Section: Top Research Domains & Growth
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Domain Velocity & Publication Growth Rate', 14, y);
  y += 6;
  
  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, pageWidth - 28, 8, 'F');
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.setFont('helvetica', 'bold');
  doc.text('Domain', 18, y + 5.5);
  doc.text('Total Publications', 100, y + 5.5, { align: 'right' });
  doc.text('Growth Rate (%)', 150, y + 5.5, { align: 'right' });
  doc.text('Status', pageWidth - 18, y + 5.5, { align: 'right' });
  y += 9;
  
  doc.setFont('helvetica', 'normal');
  (trendsData?.analytics || []).forEach((row, i) => {
    if (i % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(14, y - 1, pageWidth - 28, 7, 'F');
    }
    doc.setTextColor(15, 23, 42);
    doc.text(row.domain, 18, y + 4);
    doc.text(String(row.totalPublications), 100, y + 4, { align: 'right' });
    
    doc.setFont('helvetica', 'bold');
    const isPositive = row.growthRate >= 0;
    doc.setTextColor(isPositive ? 16 : 239, isPositive ? 185 : 68, isPositive ? 129 : 68);
    doc.text(`${row.growthRate > 0 ? '+' : ''}${row.growthRate}%`, 150, y + 4, { align: 'right' });
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(row.growthRate > 15 ? 'High Growth' : 'Steady', pageWidth - 18, y + 4, { align: 'right' });
    
    y += 7;
  });
  
  addFooter(doc, 1, 1);
  doc.save(`Research_Insights_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};

/**
 * 5. Export AI Innovation & Commercialization PDF
 */
export const exportAIInnovationPDF = (idea, analysisResult) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  addHeader(doc, 'Innovation Intelligence', 'AI Commercialization Advisory');
  
  let y = 38;
  
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Research Commercialization Report', 14, y);
  y += 6;
  
  // Idea box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, y, pageWidth - 28, 18, 2, 2, 'FD');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text('EVALUATED RESEARCH IDEA:', 18, y + 5);
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'italic');
  const truncatedIdea = idea.length > 120 ? idea.substring(0, 117) + '...' : idea;
  doc.text(`"${truncatedIdea}"`, 18, y + 12);
  
  y += 24;
  
  if (analysisResult) {
    // 1. TRL & Impact
    doc.setFontSize(11);
    doc.setTextColor(99, 102, 241);
    doc.setFont('helvetica', 'bold');
    doc.text('Technology Readiness & Potential Impact', 14, y);
    y += 5;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    if (analysisResult.trl) {
      doc.text(`TRL Assessment: ${analysisResult.trl}`, 18, y);
      y += 5;
    }
    if (analysisResult.impact) {
      const splitImpact = doc.splitTextToSize(`Impact: ${analysisResult.impact}`, pageWidth - 36);
      doc.text(splitImpact, 18, y);
      y += splitImpact.length * 4.5;
    }
    y += 4;
    
    // 2. Commercialization Strategies
    if (analysisResult.commercialization) {
      doc.setFontSize(11);
      doc.setTextColor(99, 102, 241);
      doc.setFont('helvetica', 'bold');
      doc.text('Commercialization Recommendations', 14, y);
      y += 5;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(51, 65, 85);
      analysisResult.commercialization.forEach(item => {
        doc.text(`• ${item}`, 18, y);
        y += 4.5;
      });
      y += 4;
    }
    
    // 3. Recommended Funding & Target Industries
    if (analysisResult.funding) {
      doc.setFontSize(11);
      doc.setTextColor(99, 102, 241);
      doc.setFont('helvetica', 'bold');
      doc.text('Matching Funding Programs', 14, y);
      y += 5;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(51, 65, 85);
      analysisResult.funding.forEach(item => {
        doc.text(`• ${item}`, 18, y);
        y += 4.5;
      });
    }
  }
  
  addFooter(doc, 1, 1);
  doc.save(`Innovation_Advisory_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};
